/*
  Warnings:

  - You are about to drop the column `maintenance` on the `Property` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "Property" DROP COLUMN "maintenance",
ADD COLUMN     "GymAllowed" BOOLEAN,
ADD COLUMN     "IdealFor" JSONB,
ADD COLUMN     "LockinPeriod" TEXT,
ADD COLUMN     "SecondmobileNo" TEXT,
ADD COLUMN     "Washroom" JSONB,
ADD COLUMN     "addOthertags" TEXT,
ADD COLUMN     "availabilityDay" JSONB,
ADD COLUMN     "availableAllDay" BOOLEAN,
ADD COLUMN     "bathroom" TEXT,
ADD COLUMN     "closingTime" TIMESTAMP(3),
ADD COLUMN     "commonTV" BOOLEAN,
ADD COLUMN     "cookingAllowed" BOOLEAN,
ADD COLUMN     "depositNegotiable" BOOLEAN,
ADD COLUMN     "drinking" BOOLEAN,
ADD COLUMN     "endTime" TIMESTAMP(3),
ADD COLUMN     "expectedRent" DOUBLE PRECISION,
ADD COLUMN     "feedback" TEXT,
ADD COLUMN     "flatParking" JSONB,
ADD COLUMN     "gateClosingTime" TIMESTAMP(3),
ADD COLUMN     "gender" JSONB,
ADD COLUMN     "guardiansStay" BOOLEAN,
ADD COLUMN     "isBusinessRunning" JSONB,
ADD COLUMN     "laundry" JSONB,
ADD COLUMN     "leaseDuration" TEXT,
ADD COLUMN     "lift" JSONB,
ADD COLUMN     "maintenanceAmount" DOUBLE PRECISION,
ADD COLUMN     "maintenanceExtra" BOOLEAN,
ADD COLUMN     "mess" BOOLEAN,
ADD COLUMN     "monthlyMaintenance" JSONB,
ADD COLUMN     "noOfAvailableSlots" TEXT,
ADD COLUMN     "otherFeatures" JSONB,
ADD COLUMN     "parkingType" JSONB,
ADD COLUMN     "pgAmenities" JSONB,
ADD COLUMN     "placeisavailablefor" BOOLEAN,
ADD COLUMN     "powerBackup" BOOLEAN,
ADD COLUMN     "preferredGuests" BOOLEAN,
ADD COLUMN     "propertyCondition" JSONB,
ADD COLUMN     "propertyDescription" TEXT,
ADD COLUMN     "propertyavailablefor" JSONB,
ADD COLUMN     "propertycleaned" BOOLEAN,
ADD COLUMN     "propertypainted" BOOLEAN,
ADD COLUMN     "refrigerator" BOOLEAN,
ADD COLUMN     "roomCleaning" JSONB,
ADD COLUMN     "setDirection" TEXT,
ADD COLUMN     "shownBy" TEXT,
ADD COLUMN     "smoking" BOOLEAN,
ADD COLUMN     "startTime" TIMESTAMP(3),
ADD COLUMN     "suitableFor" TEXT[],
ADD COLUMN     "unitsPropertiesavailaible" JSONB,
ADD COLUMN     "warden" JSONB,
ADD COLUMN     "waterStorageFacility" BOOLEAN,
ADD COLUMN     "waterSupply" JSONB,
ADD COLUMN     "whatsappupdates" BOOLEAN,
ADD COLUMN     "wifi" BOOLEAN;
